services:
  app:
    command: sh -c "pnpm db:migrate && pnpm dev --hostname 0.0.0.0"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
